const TABLE_NAMES = [
  "children_type",
  "pronunciation",
  "day_of_week",
  "facilitys",
  "staffs",
  "record_types",
  "m_service_items",
  "m_pronpt_items",
  "ai_prompts",
  "ai_prompt_histories",
  "text_data",
  "children",
  "pc",
  "facility_children",
  "facility_staff",
  "staff_facility_roles",
  "managers2",
  "pc_to_children",
  "temp_notes",
  "child_records",
  "service_record",
  "refresh_tokens",
  "toolbox",
  "individual_support",
];

module.exports = { TABLE_NAMES };
